[fortigates]
fgt1 ansible_host=192.168.1.85

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios
ansible_connection=ansible.netcommon.httpapi
ansible_httpapi_use_ssl=yes
ansible_httpapi_validate_certs=no
ansible_httpapi_port=20443
vdom=root
